import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Evan Glaser's Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hey there, welcome to <a href="https://www.linkedin.com/in/glaserevan/">Evan Glaser's</a> page.
        </h1>

        <p className={styles.description}>
          I'm a {' '}
          <code className={styles.code}>Cyber Security Sales Manager turned Software Engineer</code>
        </p>

        <div className={styles.grid}>
          <a href="https://www.linkedin.com/in/glaserevan/" className={styles.card}>
            <h2>LinkedIn &rarr;</h2>
            <p>Take a look at my professional profile</p>
          </a>

          <a href="https://tigertracks.herokuapp.com/" className={styles.card}>
            <h2>Tiger Tracks &rarr;</h2>
            <p>Take a look at my golf app, Tiger Tracks.</p>
          </a>

          <a
            href="https://github.com/eglaser25"
            className={styles.card}
          >
            <h2>Github &rarr;</h2>
            <p>Take a look at some of my code</p>
          </a>

          <a
            href="Evan Glaser Resume Website.pdf"
            className={styles.card}
          >
            <h2 download>Resume &rarr;</h2>
            <p>Download my Resume</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
